In [3]:
!pip install numpy

## Difference between Lists and NumPy Arrays

In [4]:
import numpy as np

# Python list
python_list = [1, 2, 3, 4, 5]

# NumPy array
numpy_array = np.array([1, 2, 3, 4, 5])

print("Python list:", python_list)
print("NumPy array:", numpy_array)
print("Type of Python list:", type(python_list))
print("Type of NumPy array:", type(numpy_array))

Python list: [1, 2, 3, 4, 5]
NumPy array: [1 2 3 4 5]
Type of Python list: <class 'list'>
Type of NumPy array: <class 'numpy.ndarray'>


## Array Creation {#array-creation}

Creating Arrays from Lists

In [5]:
import numpy as np

# 1D Array
arr1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1d)

# 2D Array (Matrix)
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2d)

# 3D Array
arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Array:\n", arr3d)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Special Array Creation Methods

In [6]:
# Arrays with zeros
zeros_arr = np.zeros((3, 4))
print("Zeros array:\n", zeros_arr)

# Arrays with ones
ones_arr = np.ones((2, 3))
print("Ones array:\n", ones_arr)

# Identity matrix
identity_arr = np.eye(3)
print("Identity matrix:\n", identity_arr)

# Array with a range
range_arr = np.arange(0, 10, 2)  # start, stop, step
print("Range array:", range_arr)

# Array with linear spacing
linspace_arr = np.linspace(0, 1, 5)  # start, stop, num_points
print("Linspace array:", linspace_arr)

# Empty array (contains garbage values)
empty_arr = np.empty((2, 2))
print("Empty array:\n", empty_arr)

# Full array with specific value
full_arr = np.full((2, 3), 7)
print("Full array:\n", full_arr)

# Random array
random_arr = np.random.random((3, 3))
print("Random array:\n", random_arr)

Zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array:
 [[1. 1. 1.]
 [1. 1. 1.]]
Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Range array: [0 2 4 6 8]
Linspace array: [0.   0.25 0.5  0.75 1.  ]
Empty array:
 [[0.25 0.5 ]
 [0.75 1.  ]]
Full array:
 [[7 7 7]
 [7 7 7]]
Random array:
 [[0.77893914 0.31647412 0.92288582]
 [0.56108057 0.87751025 0.89820175]
 [0.2732728  0.46896369 0.31810719]]


In [11]:
print(np.random.seed(0))  # For reproducibility
print("Random array with seed:\n", np.random.random((3, 3)))
print(np.random.seed(1))  # For reproducibility
print("Random array with seed:\n", np.random.random((3, 3)))

None
Random array with seed:
 [[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]]
None
Random array with seed:
 [[4.17022005e-01 7.20324493e-01 1.14374817e-04]
 [3.02332573e-01 1.46755891e-01 9.23385948e-02]
 [1.86260211e-01 3.45560727e-01 3.96767474e-01]]


## Array Attributes {#array-attributes}

In [16]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Array:\n", arr)
print("Shape:", arr.shape)           # Dimensions
print("Size:", arr.size)             # Total elements
print("Number of dimensions:", arr.ndim)
print("Data type:", arr.dtype)
print("Item size (bytes):", arr.itemsize)
print("Total bytes:", arr.nbytes)
print("Strides:", arr.strides)       # Bytes to step in each dimension

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Size: 9
Number of dimensions: 2
Data type: int64
Item size (bytes): 8
Total bytes: 72
Strides: (24, 8)


## Array Operations {#array-operations}

Arithmetic Operations

In [18]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print("a + b =", a + b)      # Addition
print("a - b =", a - b)      # Subtraction
print("a * b =", a * b)      # Multiplication
print("a / b =", a / b)      # Division
print("a ** 2 =", a ** 2)    # Power
print("a % 2 =", a % 2)      # Modulus

# Scalar operations
print("a + 10 =", a + 10)
print("a * 2 =", a * 2)


a + b = [ 6  8 10 12]
a - b = [-4 -4 -4 -4]
a * b = [ 5 12 21 32]
a / b = [0.2        0.33333333 0.42857143 0.5       ]
a ** 2 = [ 1  4  9 16]
a % 2 = [1 0 1 0]
a + 10 = [11 12 13 14]
a * 2 = [2 4 6 8]


In [22]:
a = [[1,2],[3,4]]
arr_a = np.array(a)
b = [[1,2],[3,4]]
arr_b = np.array(b)
print(arr_a * arr_b)

[[ 1  4]
 [ 9 16]]


Comparison Operations

In [23]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])

print("a == b:", a == b)
print("a > b:", a > b)
print("a <= b:", a <= b)

a == b: [False  True False  True]
a > b: [False False  True False]
a <= b: [ True  True False  True]


##  Indexing and Slicing {#indexing-slicing}

Basic Indexing

In [25]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print("arr[0]:", arr[0])        # First element
print("arr[-1]:", arr[-1])      # Last element
print("arr[1:4]:", arr[1:4])    # Slice from index 1 to 3
print("arr[::2]:", arr[::2])    # Every second element

arr[0]: 10
arr[-1]: 50
arr[1:4]: [20 30 40]
arr[::2]: [10 30 50]


2D Array Indexing

In [32]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Original array:\n", arr_2d)
print("arr_2d[0, 1]:", arr_2d[0, 1])        # Row 0, Column 1
print("arr_2d[1, :]:", arr_2d[1, :])        # Entire row 1
print("arr_2d[:, 2]:", arr_2d[:, 2])        # Entire column 2
print("arr_2d[0:2, 1:3]:\n", arr_2d[0:2, 1:3])  # Submatrix

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
arr_2d[0, 1]: 2
arr_2d[1, :]: [4 5 6]
arr_2d[:, 2]: [3 6 9]
arr_2d[0:2, 1:3]:
 [[2 3]
 [5 6]]


Boolean Indexing

In [34]:
arr = np.array([ 4, 5, 6, 7, 8, 9, 1, 2, 3])

# Boolean indexing
mask = arr > 5
print("Mask:", mask)
print("Elements greater than 5:", arr[mask])

# Multiple conditions
mask2 = (arr > 3) & (arr < 7)
print("Elements between 3 and 7:", arr[mask2])

Mask: [False False  True  True  True  True False False False]
Elements greater than 5: [6 7 8 9]
Elements between 3 and 7: [4 5 6]


Fancy Indexing

In [38]:
arr = np.array([10, 20, 30, 40, 50])

# Using integer arrays for indexing
indices = [0, 2, 4]
print("Elements at indices 0, 2, 4:", arr[indices])

# 2D fancy indexing
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
rows = [0, 1, 2]
cols = [0, 1, 2]
print("Diagonal elements:", arr_2d[rows, cols])

# 2D fancy indexing
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
rows = [0, 1, 2]
cols = [2, 1, 0]
print("opp Diagonal elements:", arr_2d[rows, cols])

Elements at indices 0, 2, 4: [10 30 50]
Diagonal elements: [1 5 9]
opp Diagonal elements: [3 5 7]


## Array Manipulation 

Reshaping Arrays

In [ ]:
import numpy as np

arr = np.arange(12)
print("Original array:", arr)

# Reshape to 3x4
reshaped = arr.reshape(3, 4)
print("Reshaped (3x4):\n", reshaped)

# Flatten array
flattened = reshaped.flatten()
print("Flattened:", flattened)

# Reshape with -1 (automatic dimension)
auto_reshape = arr.reshape(2, -1)  # -1 means "whatever is needed"
print("Auto reshape (2x6):\n", auto_reshape)
arr.reshape


Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Auto reshape (2x6):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
